language: python

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - export PATH=$HOME/.poetry/bin:$PATH
  - poetry install

script:
  - poetry run invoke prebuild
  - poetry run tox

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6-dev
      env:
        TOXENV=py36
    - os: linux
      dist: xenial
      python: 3.7-dev
      env:
        TOXENV=py37
    - os: osx
      # `xcode10.2` has Python 3.7.3.
      osx_image: xcode10.2
      env:
        TOXENV=py37
      # `language: python` tries to install Python, which fails on OSX.
      language: shell
